class BasePlugin:
    def before_write(self, book): ...
    def after_write(self, book): ...
    def before_read(self, book): ...
    def after_read(self, book): ...
    def item_after_read(self, book, item): ...
    def item_before_write(self, book, item): ...
    def html_after_read(self, book, chapter): ...
    def html_before_write(self, book, chapter): ...
