from _typeshed import Incomplete

mimetype_initialised: bool

def debug(obj) -> None: ...
def parse_string(s): ...
def parse_html_string(s): ...
def guess_type(extenstion): ...
def create_pagebreak(pageref, label: Incomplete | None = None, html: bool = True): ...
def get_headers(elem): ...
def get_pages(item): ...
def get_pages_for_items(items): ...
